name: figma_12task
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
 
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir/Avenir-Black.ttf
          weight: 900
        - asset: assets/fonts/avenir/Avenir-Book.ttf
          weight: 800
        - asset: assets/fonts/avenir/Avenir-Heavy.ttf
          weight: 500

        - asset: assets/fonts/avenir/Avenir-Light.ttf
          weight: 500

        - asset: assets/fonts/avenir/Avenir-Regular.ttf
          weight: 500
  

    - family: Jost
      fonts:
        - asset: assets/fonts/jost/Jost-SemiBold.ttf
          weight: 600
    - family: Playfair
      fonts:
        - asset: assets/fonts/playfairdislplay/PlayfairDisplay-Medium.ttf
          weight: 600
      

      
 
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
